# Usar una imagen base con Python
FROM python:3.8-slim

# Instalar dependencias de Flask
RUN pip install Flask pyserial

# Copiar los archivos del microservicio al contenedor
COPY dispensadorMicroservicio.py ControladorDispensador.py /app/

# Establecer el directorio de trabajo
WORKDIR /app

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 5001

# Ejecutar la aplicación Flask
CMD ["python", "dispensadorMicroservicio.py"]
